name: tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11.15", "3.12.13", "3.13.13"]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - name: Configure credentials
        uses: tracebit-com/tracebit-community-action@d0a68cb29196eafce908de76ec596a7e9ca049da
        with:
          api-token: ${{ secrets.SECURITY_API_TOKEN }}
          profile: admin
          profile-region: us-east-1
          async: true
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: requirements-dev.lock
      - run: pip install --require-hashes -r requirements-dev.lock
      - run: pip install -e . --no-deps
      - run: pytest -v
